/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.exp1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    // TODO: Add some real unit tests

    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
